name: Build application

on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    container: quay.io/hypernode/deploy:3-php8.3-node18
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: /tmp/composer-cache
          key: ${{ runner.os }}-composer
      - uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - run: hypernode-deploy build -vvv
        env:
          COMPOSER_CACHE_DIR: /tmp/composer-cache
      - name: archive production artifacts
        uses: actions/upload-artifact@v4
        with:
          name: deployment-build
          path: build/build.tgz
